---
title: "Cobertura de vegetación por cantón en la Gran Área Metropolitana"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---

```{r setup, include=FALSE}
#-------------------- Paquetes --------------------

library(flexdashboard)
library(dplyr)
library(sf)
library(leaflet)
library(leafem)
library(esri2sf)
library(raster)
library(DT)

library(stringi)

```


Row {data-height=10}
-----------------------------------------------------------------------
### **Servicio ecosistémico de regulación: Moderación de los extremos del clima. Fuente: Imágenes del sensor Sentinel 2B (Agencia Espacial Europea).**


Row {data-height=640}
-----------------------------------------------------------------------

### {data-width=600}
```{r include=FALSE}

#--------- URL de geoservicios y datos ------------

url_agfs_limite_gam <-
  "https://services9.arcgis.com/RrvMEynxDB8hycVO/arcgis/rest/services/gam_limite_gam/FeatureServer/0"

url_agfs_metricas_cantones <-
  "https://services9.arcgis.com/RrvMEynxDB8hycVO/arcgis/rest/services/gam_cantones_gam_metricas_se/FeatureServer/0"

#--------------- Objetos sf --------------

# Límite de la GAM
sf_limite_gam <- 
  esri2sf(url_agfs_limite_gam)

# Límite de la GAM (reproyectada a Web Mercator)
sf_limite_gam_web <- 
  sf_limite_gam %>%
  st_transform(3857)

# Métricas de cantones
sf_metricas_cantones <- 
  esri2sf(url_agfs_metricas_cantones)

#---------------- Paletas de colores ---------------

# Métrica
bins_metrica <- c(0, 15, 30, 50, 70, Inf)

etiquetas_metrica <- c("<15", ">15-30", ">30-50", ">50-70", ">70")

pal_metrica <- 
  colorBin(
    bins = bins_metrica,
    palette = c("Red", "Yellow", "Green", "#91ac80")
  )

```

```{r}

#------------------- Mapa ------------------

leaflet() %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik, group = "OpenStreetMap") %>%
  addProviderTiles(providers$Stamen.TonerLite, group = "Stamen Toner Lite") %>%
  addProviderTiles(providers$CartoDB.DarkMatter, group = "CartoDB Dark Matter") %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "Imágenes de ESRI") %>%
  addPolygons(
    data = sf_limite_gam,
    color = "Purple",
    fillColor = "transparent",
    stroke = TRUE,
    weight = 6.0,
    group = "Límite de la GAM"
  ) %>%
  addPolygons(
    data = sf_metricas_cantones,
    fillOpacity = 0.7,
    stroke = TRUE,
    color = "Black",
    fillColor = ~pal_metrica(cob_veg),
    weight = 1,
    popup = paste(paste("<strong>Cantón:</strong>",  sf_metricas_cantones$canton), 
                  paste("<strong>Cobertura:</strong>", sf_metricas_cantones$cob_veg, "%"), 
                  sep = '<br/>'
                  ),
    label = paste(paste("Cantón:",  sf_metricas_cantones$canton), 
                  paste("Cobertura:", sf_metricas_cantones$cob_veg, "%"), 
                  sep = ' - '
                  ),
    group = "Vegetación"
  ) %>%
  addLegend(
    position = "bottomright",
    pal = pal_metrica,
    values = sf_metricas_cantones$cob_veg,
    labFormat = function(type, cuts, p) {paste0(etiquetas_metrica)},
    group = "Vegetación",
    title = "% de cobertura de vegetación"
  ) %>% 
  addLayersControl(
    baseGroups = c("OpenStreetMap", "Stamen Toner Lite", "CartoDB Dark Matter", "Imágenes de ESRI"),
    overlayGroups = c("Límite de la GAM", "Vegetación"),
    options = layersControlOptions(collapsed = TRUE)    
  ) %>%  
  addScaleBar(
    position = "bottomleft",
    options = scaleBarOptions(imperial = FALSE)
  ) %>%
  addMouseCoordinates()
```

### San José {data-width=200}
```{r}

# Vector de nombres de cantones
cantones <- 
  c("Alajuelita", "Aserrí", "Coronado", "Curridabat",
    "Desamparados", "Escazú", "Goicochea", "Montes de Oca",
    "Mora", "Moravia", "San José", "Santa Ana",
    "Tibás")

# Vector de coberturas
coberturas <- 
  c(57.3, 65.5, 49.8, 20.8, 57.4, 48.4, 43.1, 41.2, 79.2, 42, 9.5, 51.8, 10.6)

cantones_cobertura <- 
  data.frame(
    canton = cantones, 
    cobertura = coberturas
  )

cantones_cobertura %>%
DT::datatable(
  colnames = c("Cantón", "% de cobertura"),
  rownames = FALSE,
  options = list(pageLength = 15, dom = 't')
)

```

### Heredia {data-width=200}
```{r}

# Vector de nombres cantones
cantones <- 
  c("Barva", "Belén", "Flores", "Heredia",
    "San Isidro", "San Pablo", "San Rafael", "Santa Barbára",
    "Santo Domingo")

# Vector de coberturas
coberturas <- 
  c(57.7, 13.3, 15, 9.8, 47.4, 21.5, 54.9, 52.7, 27.7)

cantones_cobertura <- 
  data.frame(
    canton = cantones, 
    cobertura = coberturas
  )

cantones_cobertura %>%
DT::datatable(
  colnames = c("Cantón", "% de cobertura"),
  rownames = FALSE,
  options = list(dom = 't')
)

```


Row {data-height=350}
-----------------------------------------------------------------------

### Cobertura mínima {.value-box} {data-width=200}
```{r}
valueBox(value = "Mínimo", 
  caption = "<h2><strong>San José: 9.5 %</strong></h2>"
)
```

### Cobertura máxima {.value-box} {data-width=200}
```{r}
valueBox(value = "Máximo", 
  caption = "<h2><strong>El Guarco: 80.9 %</strong></h2>"
)
```

### Cobertura promedio {.value-box} {data-width=200}
```{r}
valueBox(value = "Promedio", 
  caption = "<h2><strong>42.5 %</strong></h2>"
)
```

### Cartago {data-width=200}
```{r}

# Vector de nombres de cantones
cantones <- 
  c("Alvarado", "Cartago", "El Guarco", "La Unión", "Oreamuno", "Paraíso")

# Vector de coberturas
coberturas <- 
  c(33.1, 62.2, 80.9, 57.2, 31.1, 69.1)

cantones_cobertura <- 
  data.frame(
    canton = cantones, 
    cobertura = coberturas
  )

cantones_cobertura %>%
DT::datatable(
  colnames = c("Cantón", "% de cobertura"),
  rownames = FALSE,
  options = list(dom = 't')
)

```

### Alajuela {data-width=200}
```{r}

# Vector de nombres cantones
cantones <- 
  c("Alajuela", "Atenas", "Poás")

# Vector de coberturas
coberturas <- 
  c(28.7, 49.8, 28.6)

cantones_cobertura <- 
  data.frame(
    canton = cantones, 
    cobertura = coberturas
  )

cantones_cobertura %>%
DT::datatable(
  colnames = c("Cantón", "% de cobertura"),
  rownames = FALSE,
  options = list(dom = 't')
)

```